# Generated by Django 4.2.7 on 2024-03-13 09:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("TidalLane", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Test",
            new_name="tidallane",
        ),
    ]
