# Generated by Django 4.2.7 on 2024-03-13 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("TidalLane", "0002_rename_test_tidallane"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tidallane",
            name="name",
        ),
        migrations.AddField(
            model_name="tidallane",
            name="arrivetime",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tidallane",
            name="carnum",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tidallane",
            name="passtime",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tidallane",
            name="speed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tidallane",
            name="waittime",
            field=models.IntegerField(default=0),
        ),
    ]
